apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    myCustomLabelForServiceSelctor: webapp-for-selector
    release: "0"
spec:
  containers:
  - name: wepapp-container
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-release-0-5
  labels:
    myCustomLabelForServiceSelctor: webapp-for-selector
    release: "0-5"
spec:
  containers:
  - name: wepapp-container
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
    