apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    myCustomLabelForServiceSelctor: queue-for-selector
    release: "1"
spec:
  containers:
  - name: wepapp-container
    image: richardchesterwood/k8s-fleetman-queue:release1
