apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue-svc

spec:
  selector:
    myCustomLabelForServiceSelctor: queue-for-selector
    release: "1"
  ports:
    - name: http
      port: 8161
      nodePort: 30010
  type: NodePort
