apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp-replicaset-svc

spec:
  selector:
    myCustomLabelForServiceSelctor: webapp-replicaset-selector
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort
