
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release1
        resources:
          requests:
            memory: 1000Mi
            cpu: 1
          limits: 
            memory: 1000Mi # if actual memory-usage of container exceeds the limit, then container will be killed, and pod will attempt to restart.
            cpu: 1 # if actual cpu-usage of container exceeds the limit, then container will be clamped, and pod/container will continue to run.



